print("== Basic Tests ==");
print("1+1="+1+1);
print("text "+"text");
print(2+2);
print(2-2);
print(2*2);
print(2/2);
print(2>2);
print(2==2);
print(2<2);
print("== Function Tests ==");
fn triple(x){
	x*3;
}
fn msum(x,y){
	let z = x+x;
	y*z;
}
fn zeroparam(){
	print("look ma! No parameters");
}

let y = triple(3);
print(y);
let w = msum(2,3);
print(w);

print("== If Tests ==");
if 3<5 {
	print("3 is less than 5");
}
if 5>3 {
	print("5 is greater than 3");
}
if 4>=4{
	print("4 is ge 4");
}
if 4<=4{
	print("4 is le 4");
}
if 4==4{
	print("4 is eq to 4");
}
if 3!=5{
	print("3 is neq to 5");
}
if 6==4{
	print("critical error in logic!!");
} else {
	print("raw else works");
}
if false{
	print("yoyo");
} else if true {
	print("chained if works");
}
if "hi"=="hi" {
	print("text equality works");
}

print("== Loop Tests ==");

let l = 0;

loop while 5>l {
	print("conditional loop iter! | "+l);
	let m = l+1;
	let l = m;
}

loop n in 1 to 4 {
	print("incrementing loop iter! | "+n);
}