print("== Basic Tests ==");
print("1+1="+1+1);
print("text "+"text");
print(2+2);

print("== Function Tests ==");
fn triple(x){
	x*3;
}
let y = triple(3);
print(y);

print("== If Tests ==");
if 3<5 {
	print("3 is less than 5");
}

if 5>3 {
	print("5 is greater than 3");
}

if 4>=4{
	print("4 is ge 4");
}

if 4<=4{
	print("4 is le 4");
}

if 4==4{
	print("4 is eq to 4");
}
if 3!=5{
	print("3 is neq to 5");
}
if 6==4{
	print("critical error in logic!!");
} else {
	print("raw else works");
}
if false{
	print("yoyo");
} else if true {
	print("chained if works");
}

if "hi"=="hi" {
	print("text equality works");
}